import fs from 'node:fs/promises';
import path from 'node:path';
import { AwsClient } from 'aws4fetch';
import type { Config } from '../../config.ts';

/* Where uploaded files live: a local folder in development, any S3-compatible bucket in production
   (Cloudflare R2, AWS S3, Backblaze B2…). Keys are generated by us, never taken from the request. */

export interface Storage {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
  /** a direct public URL for public files when the bucket has one (else the API serves them) */
  publicUrl(key: string): string | null;
}

const KEY_RE = /^[a-z0-9][a-z0-9/_.-]{0,200}$/i;
const checkKey = (key: string) => {
  if (!KEY_RE.test(key) || key.includes('..')) throw new Error(`bad storage key: ${key}`);
  return key;
};

export class LocalStorage implements Storage {
  private root: string;
  constructor(dir: string) {
    this.root = path.resolve(dir);
  }
  private file = (key: string) => path.join(this.root, checkKey(key));
  async put(key: string, body: Buffer) {
    const f = this.file(key);
    await fs.mkdir(path.dirname(f), { recursive: true });
    await fs.writeFile(f, body);
  }
  async get(key: string) {
    return fs.readFile(this.file(key)).catch(() => null);
  }
  async delete(key: string) {
    await fs.rm(this.file(key), { force: true });
  }
  publicUrl() {
    return null;
  }
}

export class S3Storage implements Storage {
  private client: AwsClient;
  private endpoint: string;
  constructor(private config: Config) {
    this.client = new AwsClient({ accessKeyId: config.S3_ACCESS_KEY_ID!, secretAccessKey: config.S3_SECRET_ACCESS_KEY!, service: 's3', region: config.S3_REGION });
    this.endpoint = config.S3_ENDPOINT!.replace(/\/$/, '');
  }
  /** public/… keys go to the public bucket when there is one */
  private bucket = (key: string) => (key.startsWith('public/') && this.config.S3_PUBLIC_BUCKET ? this.config.S3_PUBLIC_BUCKET : this.config.S3_BUCKET!);
  private url = (key: string) => `${this.endpoint}/${this.bucket(key)}/${checkKey(key).split('/').map(encodeURIComponent).join('/')}`;
  async put(key: string, body: Buffer, contentType: string) {
    const res = await this.client.fetch(this.url(key), { method: 'PUT', body, headers: { 'content-type': contentType } });
    if (!res.ok) throw new Error(`storage put ${res.status}: ${(await res.text()).slice(0, 200)}`);
  }
  async get(key: string) {
    const res = await this.client.fetch(this.url(key));
    if (res.status === 404) return null;
    if (!res.ok) throw new Error(`storage get ${res.status}`);
    return Buffer.from(await res.arrayBuffer());
  }
  async delete(key: string) {
    const res = await this.client.fetch(this.url(key), { method: 'DELETE' });
    if (!res.ok && res.status !== 404) throw new Error(`storage delete ${res.status}`);
  }
  publicUrl(key: string) {
    // only a dedicated public bucket may be read directly; otherwise the API serves public files itself
    return this.config.S3_PUBLIC_URL && this.config.S3_PUBLIC_BUCKET && key.startsWith('public/') ? `${this.config.S3_PUBLIC_URL.replace(/\/$/, '')}/${key}` : null;
  }
}

export const createStorage = (config: Config): Storage => (config.STORAGE === 's3' ? new S3Storage(config) : new LocalStorage(config.UPLOAD_DIR));
