/* GENERATED by scripts/extract-mockups.ts from ../design/src/mock-assets.js — do not edit by hand.
   Garment photos and masks: apps/web/public/mockups/<view>.jpg and <view>-mask.png (900 × 1125).
   ref: average brightness of the garment (white = no recolour), pxcm: photo pixels per cm,
   rot/curve: how the fabric is turned/bent at the print area, place: print areas (x, y in photo px;
   min/max/d: smallest, largest and default design width in cm), credit: photo source (Unsplash). */
import type { GarmentManifest } from './types';

export type GarmentView = 'tee' | 'model' | 'polo' | 'shirt' | 'hoodie' | 'cap' | 'tote';

/** placement keys available on each garment view */
export interface GarmentPlacements {
  tee: 'lc' | 'cc';
  model: 'lc' | 'cc';
  polo: 'lc' | 'rc';
  shirt: 'pk' | 'ap';
  hoodie: 'cc' | 'lc';
  cap: 'fr';
  tote: 'cc' | 'bc';
}

export type PlacementKey = GarmentPlacements[GarmentView];

export const GARMENT_VIEWS: readonly GarmentView[] = [
  'tee',
  'model',
  'polo',
  'shirt',
  'hoodie',
  'cap',
  'tote',
];

export const GARMENTS: Record<GarmentView, GarmentManifest> = {
  tee: {
    w: 900,
    h: 1125,
    ref: 0.8426,
    pxcm: 10.029,
    rot: 0,
    curve: 0,
    place: {
      lc: { n: 'Left chest', x: 567.3, y: 450, min: 5, max: 10, d: 8 },
      cc: { n: 'Centre chest', x: 445.2, y: 541.6, min: 10, max: 28, d: 22 },
    },
    credit: 'https://unsplash.com/photos/acn5ERAeSb4',
  },
  model: {
    w: 900,
    h: 1125,
    ref: 0.7891,
    pxcm: 9,
    rot: -2,
    curve: 0.25,
    place: {
      lc: { n: 'Left chest', x: 615, y: 512, min: 5, max: 10, d: 8 },
      cc: { n: 'Centre chest', x: 530, y: 632, min: 10, max: 28, d: 22 },
    },
    credit: 'https://unsplash.com/photos/ogmenj2NGho',
  },
  polo: {
    w: 900,
    h: 1125,
    ref: 0.9454,
    pxcm: 8.691,
    rot: 0,
    curve: 0,
    place: {
      lc: { n: 'Left chest', x: 565.7, y: 430.7, min: 5, max: 10, d: 8 },
      rc: { n: 'Right chest', x: 338.1, y: 430.7, min: 5, max: 10, d: 8 },
    },
    credit: 'https://unsplash.com/photos/F5i3PZXYkvY',
  },
  shirt: {
    w: 900,
    h: 1125,
    ref: 0.8311,
    pxcm: 10.125,
    rot: 0,
    curve: 0,
    place: {
      pk: { n: 'On the pocket', x: 587.8, y: 523.1, min: 4, max: 7, d: 6 },
      ap: { n: 'Above the pocket', x: 587.8, y: 390.9, min: 5, max: 9, d: 7 },
    },
    credit: 'https://unsplash.com/photos/ve2dwNxZ5Rg',
  },
  hoodie: {
    w: 900,
    h: 1125,
    ref: 0.9457,
    pxcm: 8.308,
    rot: 0,
    curve: 0,
    place: {
      cc: { n: 'Centre chest', x: 432.7, y: 635.2, min: 10, max: 20, d: 14 },
      lc: { n: 'Left chest', x: 562.5, y: 431, min: 5, max: 9, d: 8 },
    },
    credit: 'https://unsplash.com/photos/kJXGTOY1wLQ',
  },
  cap: {
    w: 900,
    h: 1125,
    ref: 0.874,
    pxcm: 26.743,
    rot: 0,
    curve: 0.55,
    place: {
      fr: { n: 'Front', x: 456.4, y: 462.9, min: 4, max: 11, d: 9 },
    },
    credit: 'https://unsplash.com/photos/DT7ercyDWjs',
  },
  tote: {
    w: 900,
    h: 1125,
    ref: 0.7431,
    pxcm: 16.575,
    rot: 0,
    curve: 0,
    place: {
      cc: { n: 'Centre', x: 451.9, y: 678.8, min: 8, max: 28, d: 22 },
      bc: { n: 'Bottom corner', x: 648.8, y: 900, min: 5, max: 10, d: 7 },
    },
    credit: 'https://unsplash.com/photos/smTDI-z1rlY',
  },
};
