/// <reference types="node" />
/* Extracts the garment photos + masks from the design prototype's mock-assets.js.

   Writes apps/web/public/mockups/<view>.jpg and <view>-mask.png (the decoded data URLs, byte for byte)
   and generates src/garments.ts: a typed manifest with the numbers the engine needs (no data URLs).

   Usage (from packages/stitch):  npx tsx scripts/extract-mockups.ts [path/to/mock-assets.js]
   Default source: ../design/src/mock-assets.js next to the platform folder. */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

interface RawPlacement {
  n: string;
  x: number;
  y: number;
  min: number;
  max: number;
  d: number;
}
interface RawView {
  img: string;
  mask: string;
  w: number;
  h: number;
  ref: number;
  pxcm: number;
  rot: number;
  curve: number;
  place: Record<string, RawPlacement>;
  src: string;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, '..');
const PLATFORM = resolve(PKG, '../..');
const SRC = resolve(process.argv[2] ?? resolve(PLATFORM, '../design/src/mock-assets.js'));
const OUT_DIR = resolve(PLATFORM, 'apps/web/public/mockups');
const MANIFEST = resolve(PKG, 'src/garments.ts');

/* mock-assets.js is `const MOCK={...json...};` after a comment line: parse it as JSON, never eval it */
const text = readFileSync(SRC, 'utf8');
const m = /const\s+MOCK\s*=\s*(\{[\s\S]*\})\s*;?\s*$/.exec(text);
if (!m || !m[1]) throw new Error(`No "const MOCK={...}" object found in ${SRC}`);
const MOCK = JSON.parse(m[1]) as Record<string, RawView>;

const JPEG_MAGIC = Buffer.from([0xff, 0xd8, 0xff]);
const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

function decode(dataUrl: string, mime: string, magic: Buffer, what: string): Buffer {
  const prefix = `data:${mime};base64,`;
  if (!dataUrl.startsWith(prefix)) throw new Error(`${what}: expected a ${prefix}… data URL`);
  const b64 = dataUrl.slice(prefix.length);
  const bytes = Buffer.from(b64, 'base64');
  /* byte-identical check: re-encoding must give back exactly the base64 we were given */
  if (bytes.toString('base64') !== b64) throw new Error(`${what}: base64 does not round-trip`);
  if (!bytes.subarray(0, magic.length).equals(magic)) throw new Error(`${what}: not a ${mime} file`);
  return bytes;
}

const isIdent = (k: string) => /^[A-Za-z_$][\w$]*$/.test(k);
const key = (k: string) => (isIdent(k) ? k : `'${k}'`);
const str = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const num = (n: number) => {
  if (typeof n !== 'number' || !Number.isFinite(n)) throw new Error(`not a finite number: ${String(n)}`);
  return String(n);
};

mkdirSync(OUT_DIR, { recursive: true });
const views = Object.keys(MOCK);
const placeKeys = new Set<string>();
const entries: string[] = [];
const placements: string[] = [];
let bytes = 0;

for (const view of views) {
  const v = MOCK[view]!;
  const jpg = decode(v.img, 'image/jpeg', JPEG_MAGIC, `${view}.img`);
  const png = decode(v.mask, 'image/png', PNG_MAGIC, `${view}.mask`);
  writeFileSync(resolve(OUT_DIR, `${view}.jpg`), jpg);
  writeFileSync(resolve(OUT_DIR, `${view}-mask.png`), png);
  bytes += jpg.length + png.length;

  const pk = Object.keys(v.place);
  if (!pk.length) throw new Error(`${view}: no placements`);
  pk.forEach((k) => placeKeys.add(k));
  placements.push(`  ${key(view)}: ${pk.map(str).join(' | ')};`);
  const place = pk
    .map((k) => {
      const p = v.place[k]!;
      return `      ${key(k)}: { n: ${str(p.n)}, x: ${num(p.x)}, y: ${num(p.y)}, min: ${num(p.min)}, max: ${num(p.max)}, d: ${num(p.d)} },`;
    })
    .join('\n');
  entries.push(
    `  ${key(view)}: {\n` +
      `    w: ${num(v.w)},\n    h: ${num(v.h)},\n    ref: ${num(v.ref)},\n    pxcm: ${num(v.pxcm)},\n` +
      `    rot: ${num(v.rot ?? 0)},\n    curve: ${num(v.curve ?? 0)},\n` +
      `    place: {\n${place}\n    },\n` +
      `    credit: ${str(v.src)},\n  },`,
  );
  console.log(`${view.padEnd(7)} ${String(jpg.length).padStart(7)} B jpg  ${String(png.length).padStart(6)} B mask`);
}

const rel = relative(PLATFORM, SRC).split('\\').join('/');
const out = `/* GENERATED by scripts/extract-mockups.ts from ${rel} — do not edit by hand.
   Garment photos and masks: apps/web/public/mockups/<view>.jpg and <view>-mask.png (900 × 1125).
   ref: average brightness of the garment (white = no recolour), pxcm: photo pixels per cm,
   rot/curve: how the fabric is turned/bent at the print area, place: print areas (x, y in photo px;
   min/max/d: smallest, largest and default design width in cm), credit: photo source (Unsplash). */
import type { GarmentManifest } from './types';

export type GarmentView = ${views.map(str).join(' | ')};

/** placement keys available on each garment view */
export interface GarmentPlacements {
${placements.join('\n')}
}

export type PlacementKey = GarmentPlacements[GarmentView];

export const GARMENT_VIEWS: readonly GarmentView[] = [${views.map(str).join(', ')}];

export const GARMENTS: Record<GarmentView, GarmentManifest> = {
${entries.join('\n')}
};
`;
writeFileSync(MANIFEST, out);
console.log(
  `wrote ${views.length} views (${(bytes / 1024).toFixed(0)} KB) to ${relative(PLATFORM, OUT_DIR)}/ and ${relative(PLATFORM, MANIFEST)}`,
);
console.log(`placement keys: ${[...placeKeys].join(', ')}`);
